### ISSUE TITLE
Style Header

### ISSUE THREAD

**Issue by JasonFritsche** [gavinr/stl-live-crime#22]
Hi Gavin! I'd like to contribute to your project. Is it ok to work on styling the header? If so, please assign this Issue to me and provide any suggestions/guidance.

Thank you!

**Comment by gavinr** [comment]
Thank you for volunteering - what were you thinking about changing?

**Comment by JasonFritsche** [comment]
I am suggesting style changes for the header. Perhaps something simple like I did for my [News From the Wormhole](https://jasonfritsche.github.io/news-from-the-wormhole/) project. It's a simple blue header with App title on the left, and navigation links on the right. Thoughts?

**Comment by gavinr** [comment]
I am open to making the page look better from a design perspective. I think if you made a header color, it would make sense to integrate that style into the rest of the page, for example:

- perhaps a border or background of the selected item in the list would be the same or complimentary color?
- perhaps a tie-in to the "about" popup?

I am open to this, but would want to reserve the right to not include it if turns out not to be what i'm thinking - perhaps if you wanted to start with a mockup that would help?

**Comment by JasonFritsche** [comment]
@gavinr I'll fork the repo and play with some styles over the course of the next few days. I'll share some screenshots/gifs with you. Thank you.
